
FROM node:20-alpine


WORKDIR /app


RUN apk add --no-cache postgresql-client python3 make g++


COPY package.json package-lock.json tsconfig*.json ./


RUN npm install


COPY . .


RUN npm run build


EXPOSE 3000


CMD ["sh", "-c", "npm run migration:run && npm run seed:prod && npm run start:prod"]
